[package]
name = "todo_baggins"
version = "0.1.0"
authors = ["Matouš Volf <git@matousvolf.cz>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.43", features = ["serde", "unstable-locales"] }
# Remember to update the CLI as well.
dioxus = { version = "0.7.3", features = ["fullstack", "router"] }
# TODO: Remove this once https://github.com/DioxusLabs/dioxus/issues/4765 is resolved.
dioxus-html = { version = "0.7.3", features = ["serialize"] }
feruca = { version = "0.12.0" }
serde = { version = "1.0.228" }
serde_json = { version = "1.0.149" }
serde_with = { version = "3.16.1", features = ["chrono_0_4"] }
tracing = "0.1.44"
unic-langid-impl = { version = "0.9.6", features = ["serde"] }
validator = { version = "0.21.0", features = ["derive"] }

# Remember to update the CLI as well.
diesel = { version = "2.3.6", features = [
    "chrono",
    "postgres",
    "postgres_backend",
    "serde_json",
], optional = true }
diesel_migrations = { version = "2.3.1", features = [
    "postgres",
], optional = true }
rand = { version = "0.10.0", optional = true }
time = { version = "0.3.45", optional = true }
tokio = { version = "1.49.0", optional = true }

async-std = { version = "1.13.2", optional = true }
dioxus-i18n = "0.5.1"
voca_rs = "1.15.2"
load-dotenv = "0.1.2"
# TODO: Switch to upstream once it merges the changes.
dioxus-free-icons = { git = "https://github.com/matous-volf/dioxus-free-icons", rev = "6488400003a3d6829e771a84a565c5c5f08a9aa0", features = [
    "font-awesome-regular",
    "font-awesome-solid",
] }

[features]
default = ["web"]
web = ["dioxus/web", "dep:async-std"]
mobile = ["dioxus/mobile", "dep:async-std"]
desktop = ["dioxus/desktop"]
server = [
    "dioxus/server",
    "dep:diesel",
    "dep:diesel_migrations",
    "dep:rand",
    "dep:time",
    "dep:tokio",
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
