[package]
name = "todo-baggins"
version = "0.1.0"
authors = ["Matouš Volf <git@matousvolf.cz>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.41", features = ["serde", "unstable-locales"] }
dioxus = { version = "0.6.3", features = ["fullstack", "router"] }
feruca = { version = "0.11.4" }
serde = { version = "1.0.219" }
serde_json = { version = "1.0.142" }
serde_with = { version = "3.14.0", features = ["chrono_0_4"] }
tracing = "0.1.41"
unic-langid-impl = { version = "0.9.6", features = ["serde"] }
validator = { version = "0.20.0", features = ["derive"] }

diesel = { version = "2.2.12", features = ["chrono", "postgres", "postgres_backend", "serde_json"], optional = true }
diesel_migrations = { version = "2.2.0", features = ["postgres"], optional = true }
dotenvy = { version = "0.15.7", optional = true }
time = { version = "0.3.41", optional = true }

async-std = { version = "1.13.1", optional = true }
dioxus-i18n = { version = "0.4.3", optional = true }
dioxus-query = { version = "0.6.1", optional = true }
voca_rs = { version = "1.15.2", optional = true }

[features]
default = ["web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
web = [
    "dioxus/web",
    "dep:async-std",
    "dep:dioxus-query",
    "dep:dioxus-i18n",
    "dep:voca_rs"
]
server = [
    "dioxus/server",
    "dep:diesel",
    "dep:diesel_migrations",
    "dep:dotenvy",
    "dep:time",
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
