---
services:
  app:
    build:
      dockerfile: docker/prod/app/Dockerfile
    networks:
      - default
    restart: always
    depends_on: ["db"]

  db:
    image: postgres:16.11-alpine3.23@sha256:4327b9fd295502f326f44153a1045a7170ddbfffed1c3829798328556cfd09e2
    volumes: ["db_data:/var/lib/postgresql/data"]
    networks:
      - default
    environment:
      POSTGRES_DB: todo_baggins
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: always

volumes:
  db_data:
