---
services:
  app:
    build:
      dockerfile: docker/prod/app/Dockerfile
    networks:
      - default
    restart: always
    depends_on: ["db"]

  db:
    image: postgres:16.14-alpine3.23@sha256:a5824d29054ed662a86533ab89919d3d7e79987a16e22555f8a98b8a7be45de4
    volumes: ["db_data:/var/lib/postgresql/data"]
    networks:
      - default
    environment:
      POSTGRES_DB: todo_baggins
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: always

volumes:
  db_data:
