---
services:
  app:
    build:
      dockerfile: docker/prod/app/Dockerfile
    networks:
      - default
    restart: always
    depends_on: ["db"]

  db:
    image: postgres:16.14-alpine3.23@sha256:c95dee655b8a0743021bdbd2d21abb7ef2fd520c5df39bd328798769c049648f
    volumes: ["db_data:/var/lib/postgresql/data"]
    networks:
      - default
    environment:
      POSTGRES_DB: todo_baggins
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: always

volumes:
  db_data:
