services:
  app:
    build:
      dockerfile: docker/prod/app/Dockerfile
    restart: always
    ports: [ "8000:8000" ]
    depends_on: [ "db" ]

  db:
    image: postgres:16.4-bookworm
    volumes: [ "db_data:/var/lib/postgresql/data" ]
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_DB: todo_baggins
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    restart: always

volumes:
  db_data:
