---
name: Hadolint check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Hadolint check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check
        uses: https://github.com/hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: "*Dockerfile*"
          recursive: true
