---
name: Rust check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Rust check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check
        uses: https://codeberg.org/matous-volf/action-rust-check@89a31dc65ef1d8d666da28b061da4d536c58494a # v14.0.0
        with:
          system_dependencies: |
            # renovate: repology=alpine_3_24/build-base
            build-base=0.5-r4
            # renovate: repology=alpine_3_24/gcompat
            gcompat=1.1.0-r4
            # renovate: repology=alpine_3_24/glib-dev
            glib-dev=2.88.1-r1
            # renovate: repology=alpine_3_24/musl-dev
            musl-dev=1.2.6-r2
            # renovate: repology=alpine_3_24/openssl-dev
            openssl-dev=3.5.8-r0
            # renovate: repology=alpine_3_24/openssl-libs-static
            openssl-libs-static=3.5.7-r0
            # renovate: repology=alpine_3_24/webkit2gtk-4.1-dev
            webkit2gtk-4.1-dev=2.48.7-r0
          pre_command: |
            ln -s .env.example .env
            touch assets/tailwind.css
          check_advisories: false
          lint_docs: false
          run_tests: false
          check_semver: false
          check_msrv: false
          feature_powerset_depth: 1
