---
name: Rust check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Rust check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Dependencies installation
        run: |
          DEPENDENCIES=(
            # renovate: repology=ubuntu_24_04/gtk+3.0
            libgtk-3-dev=3.24.41-4ubuntu1.3
            # renovate: repology=ubuntu_24_04/webkit2gtk
            libjavascriptcoregtk-4.1-dev=2.52.3-0ubuntu0.24.04.1
            # renovate: repology=ubuntu_24_04/libsoup3
            libsoup-3.0-dev=3.4.4-5ubuntu0.7
            # renovate: repology=ubuntu_24_04/webkit2gtk
            libwebkit2gtk-4.1-dev=2.52.3-0ubuntu0.24.04.1
            # renovate: repology=ubuntu_24_04/xdotool
            libxdo-dev=1:3.20160805.1-5build1
          )
          apt-get update && apt-get install -y "${DEPENDENCIES[@]}"

      - name: Code checkout
        uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: .env symlink creation
        run: ln -s .env.example .env

      - name: Tailwind CSS output creation
        run: touch assets/tailwind.css

      - name: Check
        uses: https://codeberg.org/matous-volf/action-rust-check@f0c0a5b4c3079b21f07a684d9c9b7ef642097f1a # v1.0.0
        with:
          rust_version: 1.96.0
          run_tests: false
