---
name: Stylelint check
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
permissions: {}
jobs:
  check:
    name: Stylelint check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check
        uses: https://codeberg.org/matous-volf/action-stylelint-check@9f79ab9c2e0bcf6e33a1abf89fe50cd55b4b5114 # v1.0.1
