name: conventional pull requests

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  validate-pr-title:
    runs-on: ubuntu-22.04
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["build","chore","ci","docs","feat","fix","perf","refactor","revert","style","test"]'
          add_label: 'false'
