name: conventional commits

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  build:
    name: conventional commits
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: conventional commits check
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
